name: CI/CD to JFrog Registry

on:
  push:
    branches: [ "main" ]
#  pull_request:

jobs:
  build:
    name: build & push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
 
      - name: Create and Push image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: zhiyao07102/jd_test_rep/test_image
            tags: v1, latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }} 

