name: CI/CD to JFrog Registry

on:
  push:
    branches: [ "main" ]
#  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
